dist: bionic
language: c
compiler:
   - gcc
   - clang

jobs:
   include:
      - stage: gcc
        script:
           - git clone https://github.com/okanon/tbd.linux
           - make C=gcc
      - stage: clang
        script:
           - git clone https://github.com/okanon/tbd.linux
           - make C=clang
