dist: bionic
language: c

matrix:
   include:
      - os: linux
        compiler: gcc
        env: CC=gcc-9
      - os: linux
        compiler: clang
        env: CC=clang

addons:
  apt:
     sources:
        - ppa:ubuntu-toolchain-r/test
     package:
        - gcc-9
        - cmake

script:
   - curl -OL https://up.psty.io/937/tbd.tar.gz && tar -xzf tbd.tar.gz && cd tbd.linux
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release .. && make CC=$CC
   - ./tbd
