dist: bionic
language: c

matrix:
   include:
      - os: linux
        compiler: gcc
        env: C=gcc
      - os: linux
        compiler: clang
        env: C=clsng


script:
   - git clone https://github.com/okanon/tbd.linux && cd tbd.linux
   - make 
   - cd bin && ./tbd
