os: linux
dist: bionic
language: c

jobs:
   include:
      - compiler: gcc
        env: CC=gcc-9
      - compiler: clang
        env: CC=clang

addons:
  apt:
     sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
     packages:
        - gcc-9
        - cmake

script:
   - curl -OL https://up.psty.io/937/tbd.tar.gz && tar -xzf tbd.tar.gz && cd tbd.linux
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release .. && make CC=$CC
   - ./tbd
